AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GourmetSearch:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: gourmet_search/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          GOURMET_SEARCH_API_KEY: "{{resolve:secretsmanager:gourmet-search-api-key:SecretString}}"
