version: "3"
services:
  front:
    build:
      dockerfile: Dockerfile
    environment:
      LAMBDA_FUNCTION_URL: https://tzw2qnyy5ruqhqu7wblsxghnvm0vewja.lambda-url.ap-northeast-1.on.aws/
    ports:
      - 5000:5000
